# Generated by Django 4.1.7 on 2023-04-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sala',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='data_criacao',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='limite_participantes',
            new_name='max_participants',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='nome',
            new_name='name',
        ),
    ]
