# Generated by Django 4.1.7 on 2023-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_roadmap_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
