# Generated by Django 4.1.7 on 2023-06-18 20:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_document_created_remove_document_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
