# Generated by Django 4.1.7 on 2023-06-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='static/img/coruja.png', upload_to='static/img/'),
        ),
    ]
